#!/usr/bin/env bash
# Stages docs/store/app-store listing copy + screenshots into Fastlane deliver layout.
#
# From repo root:
#   bash docs/store/app-store/prepare-deliver.sh
#
# Output (gitignored except .gitignore):
#   ios/fastlane/metadata/<locale>/
#   ios/fastlane/screenshots/<locale>/
#
# Locale map (repo folder → App Store Connect language code):
#   en (root txts) → en-US
#   locales/es     → es-ES
#   locales/fr     → fr-FR
#   locales/de     → de-DE
#   locales/pt     → pt-BR
#   locales/ja     → ja
#   locales/zh-Hans → zh-Hans

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SRC="$SCRIPT_DIR"
FASTLANE_DIR="$REPO_ROOT/ios/fastlane"
META_OUT="$FASTLANE_DIR/metadata"
SHOT_OUT="$FASTLANE_DIR/screenshots"

IPHONE69="$SRC/screenshots/iphone-6.9"
IPHONE65="$SRC/screenshots/iphone-6.5"
IPAD13="$SRC/screenshots/ipad-13"

copy_field() {
  local src_file="$1"
  local dest_file="$2"
  if [[ ! -f "$src_file" ]]; then
    echo "prepare-deliver: missing $src_file" >&2
    exit 1
  fi
  # Strip a single trailing newline; keep internal newlines for description / what's new.
  perl -pe 'chomp if eof' <"$src_file" >"$dest_file"
}

stage_locale() {
  local dest_code="$1"
  local title="$2"
  local subtitle="$3"
  local keywords="$4"
  local description="$5"
  local promo="$6"
  local release_notes="$7"

  local dir="$META_OUT/$dest_code"
  mkdir -p "$dir"

  copy_field "$title" "$dir/name.txt"
  copy_field "$subtitle" "$dir/subtitle.txt"
  copy_field "$keywords" "$dir/keywords.txt"
  copy_field "$description" "$dir/description.txt"
  copy_field "$promo" "$dir/promotional_text.txt"
  copy_field "$release_notes" "$dir/release_notes.txt"

  # Shared URLs (same for every localization).
  printf '%s' 'https://decluttr.app/privacy' >"$dir/privacy_url.txt"
  printf '%s' 'https://decluttr.app' >"$dir/support_url.txt"
  printf '%s' 'https://decluttr.app' >"$dir/marketing_url.txt"
}

stage_screenshots() {
  local dest_code="$1"
  local dest="$SHOT_OUT/$dest_code"
  mkdir -p "$dest"

  # Prefer 6.5" (1284×2778 → APP_IPHONE_65) — well supported by ASC API via Fastlane.
  # Also stage 6.9" (1290×2796) and iPad 13" when present; Fastlane maps by pixel size.
  # Prefix keeps upload order stable.
  if [[ -d "$IPHONE65" ]]; then
    local n=0
    for f in "$IPHONE65"/[0-9][0-9]-*.png; do
      [[ -f "$f" ]] || continue
      n=$((n + 1))
      printf -v idx '%02d' "$n"
      cp -f "$f" "$dest/${idx}_APP_IPHONE_65_$(basename "$f")"
    done
  fi

  if [[ -d "$IPHONE69" ]]; then
    local n=0
    for f in "$IPHONE69"/[0-9][0-9]-*.png; do
      [[ -f "$f" ]] || continue
      n=$((n + 1))
      printf -v idx '%02d' "$n"
      # Name hint for frameit/deliver size detection; 1290×2796 maps to 6.7/6.9 depending on Fastlane version.
      cp -f "$f" "$dest/${idx}_APP_IPHONE_69_$(basename "$f")"
    done
  fi

  if [[ -d "$IPAD13" ]] && [[ "${SKIP_IPAD_SCREENSHOTS:-}" != "true" ]]; then
    local n=0
    for f in "$IPAD13"/[0-9][0-9]-*.png; do
      [[ -f "$f" ]] || continue
      n=$((n + 1))
      printf -v idx '%02d' "$n"
      cp -f "$f" "$dest/${idx}_APP_IPAD_PRO_3GEN_129_$(basename "$f")"
    done
  fi

  local count
  count="$(find "$dest" -maxdepth 1 -type f -name '*.png' | wc -l | tr -d ' ')"
  if [[ "$count" -eq 0 ]]; then
    echo "prepare-deliver: no screenshots staged for $dest_code" >&2
    exit 1
  fi
  echo "prepare-deliver: $dest_code screenshots → $count files"
}

# Fresh stage each run.
rm -rf "$META_OUT" "$SHOT_OUT"
mkdir -p "$META_OUT" "$SHOT_OUT"
# Keep gitignore markers if present in repo templates.
printf '%s\n' '# Auto-generated by prepare-deliver.sh' '*' '!.gitignore' >"$META_OUT/.gitignore"
printf '%s\n' '# Auto-generated by prepare-deliver.sh' '*' '!.gitignore' >"$SHOT_OUT/.gitignore"

echo "prepare-deliver: staging metadata…"

stage_locale "en-US" \
  "$SRC/title.txt" \
  "$SRC/subtitle.txt" \
  "$SRC/keywords.txt" \
  "$SRC/description.txt" \
  "$SRC/promotional-text.txt" \
  "$SRC/whats-new.txt"

# Secondary locales — same screenshot set for each (Apple requires per-locale assets if screenshots are localized).
declare -a LOCALE_MAP=(
  "es:es-ES"
  "fr:fr-FR"
  "de:de-DE"
  "pt:pt-BR"
  "ja:ja"
  "zh-Hans:zh-Hans"
)

for entry in "${LOCALE_MAP[@]}"; do
  src_code="${entry%%:*}"
  dest_code="${entry##*:}"
  loc="$SRC/locales/$src_code"
  if [[ ! -d "$loc" ]]; then
    echo "prepare-deliver: skip missing locale folder $loc"
    continue
  fi
  stage_locale "$dest_code" \
    "$loc/title.txt" \
    "$loc/subtitle.txt" \
    "$loc/keywords.txt" \
    "$loc/description.txt" \
    "$loc/promotional-text.txt" \
    "$loc/whats-new.txt"
done

# Review information (only when env is set — used if you later enable submit_for_review).
if [[ -n "${ASC_REVIEW_EMAIL:-}" ]]; then
  REVIEW_DIR="$META_OUT/review_information"
  mkdir -p "$REVIEW_DIR"
  printf '%s' "${ASC_REVIEW_EMAIL}" >"$REVIEW_DIR/email_address.txt"
  printf '%s' "${ASC_REVIEW_FIRST_NAME:-Support}" >"$REVIEW_DIR/first_name.txt"
  printf '%s' "${ASC_REVIEW_LAST_NAME:-456Labs}" >"$REVIEW_DIR/last_name.txt"
  printf '%s' "${ASC_REVIEW_PHONE:-+10000000000}" >"$REVIEW_DIR/phone_number.txt"
  printf '%s' "${ASC_REVIEW_NOTES:-Sign in with a test account if prompted. Cloud sync requires email/password or social login.}" >"$REVIEW_DIR/notes.txt"
fi

if [[ "${SKIP_SCREENSHOT_UPLOAD:-false}" == "true" ]]; then
  echo "prepare-deliver: skipping screenshots (SKIP_SCREENSHOT_UPLOAD=true)"
else
  echo "prepare-deliver: staging screenshots (en-US)…"
  stage_screenshots "en-US"
fi

# Optional: duplicate screenshots into every locale (slow; usually unnecessary — ASC falls back to primary).
if [[ "${COPY_SCREENSHOTS_TO_LOCALES:-false}" == "true" ]]; then
  echo "prepare-deliver: copying screenshots into secondary locales…"
  for entry in "${LOCALE_MAP[@]}"; do
    dest_code="${entry##*:}"
    if [[ -d "$META_OUT/$dest_code" ]]; then
      mkdir -p "$SHOT_OUT/$dest_code"
      cp -f "$SHOT_OUT/en-US/"*.png "$SHOT_OUT/$dest_code/"
    fi
  done
fi

echo "prepare-deliver: done"
echo "  metadata → $META_OUT"
echo "  screenshots → $SHOT_OUT"
echo "Next: (cd ios && bundle exec fastlane deliver_listing)"
