#!/usr/bin/env bash
# Stages docs/store/google-play listing copy + screenshots into Fastlane supply layout.
#
# From repo root:
#   bash docs/store/google-play/prepare-supply.sh
#
# Output (gitignored except .gitignore):
#   android/fastlane/metadata/android/<locale>/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SRC="$SCRIPT_DIR"
FASTLANE_DIR="$REPO_ROOT/android/fastlane"
META_OUT="$FASTLANE_DIR/metadata/android"

PHONE="$SRC/screenshots/phone"
T7="$SRC/screenshots/tablet-7"
T10="$SRC/screenshots/tablet-10"
FEATURE="$SRC/feature-graphic.png"

copy_field() {
  local src_file="$1"
  local dest_file="$2"
  if [[ ! -f "$src_file" ]]; then
    echo "prepare-supply: missing $src_file" >&2
    exit 1
  fi
  perl -pe 'chomp if eof' <"$src_file" >"$dest_file"
}

stage_locale() {
  local dest_code="$1"
  local title="$2"
  local short="$3"
  local full="$4"

  local dir="$META_OUT/$dest_code"
  mkdir -p "$dir/images/phoneScreenshots" \
    "$dir/images/sevenInchScreenshots" \
    "$dir/images/tenInchScreenshots" \
    "$dir/images"

  copy_field "$title" "$dir/title.txt"
  copy_field "$short" "$dir/short_description.txt"
  copy_field "$full" "$dir/full_description.txt"

  if [[ -f "$FEATURE" ]]; then
    cp -f "$FEATURE" "$dir/images/featureGraphic.png"
  fi
}

stage_screenshots() {
  local dest_code="$1"
  local dest="$META_OUT/$dest_code/images"

  if [[ ! -d "$PHONE" ]]; then
    echo "prepare-supply: missing phone screenshots — run export-play-screenshots.sh first" >&2
    exit 1
  fi

  local n=0
  for f in "$PHONE"/[0-9][0-9]-*.png; do
    [[ -f "$f" ]] || continue
    n=$((n + 1))
    printf -v idx '%02d' "$n"
    cp -f "$f" "$dest/phoneScreenshots/${idx}_$(basename "$f")"
  done
  if [[ "$n" -eq 0 ]]; then
    echo "prepare-supply: no phone screenshots found" >&2
    exit 1
  fi
  if [[ "$n" -gt 8 ]]; then
    echo "prepare-supply: warning — Play allows 8 phone shots; staged $n (trim export if upload fails)" >&2
  fi

  if [[ -d "$T7" ]]; then
    local i=0
    for f in "$T7"/[0-9][0-9]-*.png; do
      [[ -f "$f" ]] || continue
      i=$((i + 1))
      printf -v idx '%02d' "$i"
      cp -f "$f" "$dest/sevenInchScreenshots/${idx}_$(basename "$f")"
    done
  fi
  if [[ -d "$T10" ]]; then
    local i=0
    for f in "$T10"/[0-9][0-9]-*.png; do
      [[ -f "$f" ]] || continue
      i=$((i + 1))
      printf -v idx '%02d' "$i"
      cp -f "$f" "$dest/tenInchScreenshots/${idx}_$(basename "$f")"
    done
  fi

  echo "prepare-supply: $dest_code → $n phone screenshots"
}

rm -rf "$META_OUT"
mkdir -p "$META_OUT"
printf '%s\n' '# Auto-generated by prepare-supply.sh' '*' '!.gitignore' >"$META_OUT/.gitignore"

echo "prepare-supply: staging metadata…"

stage_locale "en-US" \
  "$SRC/title.txt" \
  "$SRC/short-description.txt" \
  "$SRC/full-description.txt"

if [[ "${SKIP_PLAY_SCREENSHOT_UPLOAD:-false}" == "true" ]]; then
  echo "prepare-supply: skipping screenshots (SKIP_PLAY_SCREENSHOT_UPLOAD=true)"
else
  stage_screenshots "en-US"
fi

declare -a LOCALE_MAP=(
  "es:es-ES"
  "fr:fr-FR"
  "de:de-DE"
  "pt:pt-BR"
  "ja:ja-JP"
  "zh-Hans:zh-CN"
)

for entry in "${LOCALE_MAP[@]}"; do
  src_code="${entry%%:*}"
  dest_code="${entry##*:}"
  loc="$SRC/locales/$src_code"
  if [[ ! -d "$loc" ]]; then
    echo "prepare-supply: skip missing locale $loc"
    continue
  fi
  stage_locale "$dest_code" \
    "$loc/title.txt" \
    "$loc/short-description.txt" \
    "$loc/full-description.txt"
  # Reuse en-US images for secondary locales (Play falls back if omitted; uploading keeps parity).
  if [[ "${COPY_SCREENSHOTS_TO_LOCALES:-true}" == "true" ]]; then
    mkdir -p "$META_OUT/$dest_code/images/phoneScreenshots" \
      "$META_OUT/$dest_code/images/sevenInchScreenshots" \
      "$META_OUT/$dest_code/images/tenInchScreenshots"
    cp -f "$META_OUT/en-US/images/phoneScreenshots/"*.png "$META_OUT/$dest_code/images/phoneScreenshots/" 2>/dev/null || true
    cp -f "$META_OUT/en-US/images/sevenInchScreenshots/"*.png "$META_OUT/$dest_code/images/sevenInchScreenshots/" 2>/dev/null || true
    cp -f "$META_OUT/en-US/images/tenInchScreenshots/"*.png "$META_OUT/$dest_code/images/tenInchScreenshots/" 2>/dev/null || true
    if [[ -f "$META_OUT/en-US/images/featureGraphic.png" ]]; then
      cp -f "$META_OUT/en-US/images/featureGraphic.png" "$META_OUT/$dest_code/images/featureGraphic.png"
    fi
  fi
done

echo "prepare-supply: done → $META_OUT"
echo "Next: (cd android && bundle exec fastlane supply_listing)"
